site_title = "ArxivDaily"
cache_max_days = 7
sources = [
    "http://export.arxiv.org/rss/cs.CL",
    "http://export.arxiv.org/rss/cs.IR",
    "http://export.arxiv.org/rss/cs.MM",
    "http://export.arxiv.org/rss/cs.CV",
    "http://export.arxiv.org/rss/cs.LG"
]
cache_url = "https://alongwy.top/ArxivDaily/cache.json"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"